version: 1.0.{build}
branches:
  only:
  - master
services:
- mssql2012sp1
- mssql2012sp1rs
- mssql2008r2sp2
- mssql2008r2sp2rs
- mssql2014
- mssql2014rs
build_script:
- ps: Write-Host 'Building...'
- ps: .\install.ps1

test_script:
- ps: Write-Host 'Testing...'
- ps: sqlcmd -S "(local)\SQL2014" -U "sa" -P "Password12!" -i tests.sql -d "master" -b
- ps: sqlcmd -S "(local)\SQL2012SP1" -U "sa" -P "Password12!" -i tests.sql -d "master" -b
- ps: sqlcmd -S "(local)\SQL2008R2SP2" -U "sa" -P "Password12!" -i tests.sql -d "master" -b
