version: 1.0.{build}
branches:
  only:
  - master
services:
- mssql2012sp1
- mssql2012sp1rs
- mssql2008r2sp2
- mssql2008r2sp2rs
- mssql2014
- mssql2014rs
- mssql2016
build_script:
- ps: Write-Host 'Building...'
test_script:
- ps: Write-Host 'Testing...'
